# Exercise 1: Data cleaning

Before doing actual data analysis, we usually first need to clean the data.
This might involve steps such as dealing with missing values and encoding categorical variables as integers.
In this exercise, you will perform such steps based on the Titanic passenger data.

1. Load the Titanic data set in `titanic.csv` located in the `data/` folder.
2. Report the number of observations with missing `Age`, for example using
   [`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html).
3. Compute the average age in the data set. Use the following approaches and compare your results:
    1.  Use pandas's
        [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html)
        method.

        *Hint:* Select the `Age` column first, then call its `mean()` method.

    2.  Convert the `Age` column to a NumPy array using
        [`to_numpy()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html).
        Experiment with NumPy's
        [`np.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
        and
        [`np.nanmean()`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)
        to see if you obtain the same results.
4. Replace all missing ages with the mean age you computed above, rounded to the nearest integer.
   You can either identify the missing values using a boolean mask and assign the mean
   age to those entries, or use
   [`fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

   Convert this updated `Age` column to integer type using
   [`astype()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html).

   *Hint:* Use `astype(int)`.

5. Generate a new column `Female` which takes on the value one if `Sex` is equal
   to `"female"` and zero if `Sex` is equal to `"male"`.
   This is called an _indicator_ or _dummy_ variable, and is useful for numerical
   analysis or regression.
   Delete the original column `Sex`.

   *Hint:* Create a new column using `df['new_column'] = values`, replacing
   `new_column` with the desired column name and `values` with the data to store.

6. Save your cleaned data set as `titanic-clean.csv` using
   [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)
   with `,` as the field separator.
   Tell `to_csv()` to *not* write the `DataFrame` index to the CSV file as it's not needed in this example.

# Solution

## Exercice 1

In [2]:
#importing libaries
import pandas as pd
import numpy as np

#Creating a spesific path to the data file. The dots are replacable with specific folders
DATA_PATH = '../../data'

#Finding and reading the data file
file = f'{DATA_PATH}/titanic.csv'

df = pd.read_csv(file)

#Finding the number of missing values in the Age column
missing_age = df['Age'].isna().sum()
missing_age

np.int64(177)

In [3]:
#Finding the average age
average_age = df['Age'].mean()
average_age

np.float64(29.69911764705882)

In [4]:
#Finding the average age using a numpy string. 
exp_age = df['Age'].to_numpy()
np.mean(exp_age)
np.nanmean(exp_age)

#Try to understand what the functions in iline 4 and 5 mean

np.float64(29.69911764705882)

In [5]:
#Updating all places with missing ages with the average age
average_age = np.round(average_age)

missing = df['Age'].fillna(average_age)
missing

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    30.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [6]:
#PART 5

df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [7]:
#Create an indicator variable Female
#df['Female'] = [1 if s == 'female' else 0 for s in df['Sex']]
(df['Sex'] == 'female').astype(int)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [8]:
#PART 6
#SAve Dataframe as CSV
df.to_csv('titanic-clean.csv')

***
# Exercise 2: Selecting subsets of data

In this exercise, you are asked to select subsets of macroeconomic data for the United States based on some criteria.

1.  Load the annual data from FRED which are located in `FRED_annual.xlsx`
    in the `data/FRED` folder.

    Print the list of columns and the number of non-missing observations.

    Since we are dealing with time series data, set the column `Year` as the `DataFrame`
    index.

2.  Print all observations for the 1960s decade using at least two different methods.

3.  Using the data in the column `GDP`, compute the annual GDP growth in percent
    and store it in the column `GDP_growth`. Select the years in which

    1.  GDP growth was above 5%.
    2.  GDP growth was negative, but inflation was still above 5% (such episodes are called "stagflation" since usually negative GDP growth is associated with low inflation).

        Use at least two methods for the stagflation selection.

    *Hint:* You can compute changes relative to the previous observation using the
    [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html)
    method.

In [38]:
#Part 1

#Find the file 
file = f'{DATA_PATH}/FRED/FRED_annual.xlsx'

#read the file
df = pd.read_excel(file)

#Printing the names of the columns
print(df.columns)

#Printing the number fo non-missing values for each column
df.count()

Index(['Year', 'GDP', 'CPI', 'UNRATE', 'FEDFUNDS', 'INFLATION'], dtype='str')

Year         72
GDP          72
CPI          72
UNRATE       72
FEDFUNDS     72
INFLATION    71
dtype: int64

In [39]:
#setting the index column to years
df = df.set_index('Year')

In [40]:
#part 2
#printing only the observations from the 60s
df.loc[1960:1969]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

In [41]:
#method 2 for only printing the observations for the 60s
df.query('Year >= 1960 & Year < 1970')

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

In [42]:
#part 3

#making a new column with the percentage change in GDP from year to year
df['GDP_change'] = df['GDP'].pct_change() * 100


#selecting only the observations with GDp change higher than or equal to 5 percent 
df.query('GDP_change >= 5')

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION  GDP_change
Year
1955   3083.0   26.8     4.4       1.8  -0.371747    7.134170
1959   3412.4   29.2     5.4       3.3   1.038062    6.931562
1962   3810.1   30.3     5.6       2.7   1.337793    6.127963
1964   4205.3   31.0     5.2       3.5   1.307190    5.764443
1965   4478.6   31.5     4.5       4.1   1.612903    6.498942
1966   4773.9   32.5     3.8       5.1   3.174603    6.593578
1972   5780.0   41.8     5.6       4.4   3.209877    5.255490
1973   6106.4   44.4     4.9       8.7   6.220096    5.647059
1976   6387.4   56.9     7.7       5.0   5.762082    5.386989
1978   7052.7   65.2     6.1       7.9   7.590759    5.535105
1984   8195.3  103.9     7.5      10.2   4.317269    7.236042
2021  21532.4  271.0     5.4       0.1   4.673619    6.151988

In [ ]:
#using query to print the observations that satisfy the conditions
df.query('GDP_change < 0 & INFLATION >= 5')

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_change
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

In [ ]:
#defining the conditions and printing the observations in df that satisfy the conditions
condition = (df['GDP_change'] < 0) & (df['INFLATION'] > 5)
df[condition]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_change
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

***
# Exercise 3: Labor market statistics for the US

In this exercise, you are asked to compute some descriptive statistics for the
unemployment rate and the labor force participation rate for the United States.
The latter is the percentage of the civilian noninstitutional population aged 16
and older who are in the labor force (employed or unemployed). Both rates are
expressed as percentages.

1.  Load the monthly time series from FRED which are located in `FRED_monthly.csv`
    in the `data/FRED` folder.

    *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically
    parse strings stored in the `DATE` column as dates.

    Since we are dealing with time series data, set the column `DATE` as the
    `DataFrame` index. Then print the list of columns and the number of non-missing
    observations.

2.  For the columns `UNRATE` (unemployment rate) and `LFPART` (labor force
    participation rate), compute and report
    the mean, minimum, and maximum values for the whole sample. Round your results
    to one decimal place.

    *Hint:* You can use the `DataFrame` methods
    [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html),
    [`min()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html), and
    [`max()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html)
    to compute the desired statistics.

    *Hint:* You can use the `DataFrame` method
    [`round()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html)
    to round the results to one decimal place.

3.  You are interested in how the average unemployment rate evolved over the last
    few decades.

    -   Add a new column `Decade` to the `DataFrame` which contains the
        starting year for each decade (e.g., this value should be 1950
        for the years 1950-1959, and so on).

        *Hint:* The decade can be computed from the column `Year` using
        truncated integer division:
        ```python
        df['Year'] // 10 * 10
        ```

    -   Write a loop to compute and report the average unemployment rate
        (column `UNRATE`) for each decade.

        Include only the decades from 1950 to 2010 for which you have all
        observations.

In [59]:
#Part 1

#locating the datafile
file = f'{DATA_PATH}/FRED/FRED_monthly.csv'

#reading the datafile and storing the data in df and automatically parsing strings stored in DATE as dates
df = pd.read_csv(file, parse_dates = ['DATE'])

#Setting the dates as the index
df = df.set_index('DATE')

#Printing the columns
print(df.columns)

#Printing the number of non-missing values for each category
df.count()

Index(['Year', 'Month', 'CPI', 'UNRATE', 'FEDFUNDS', 'REALRATE', 'LFPART'], dtype='str')

Year        936
Month       936
CPI         935
UNRATE      935
FEDFUNDS    858
REALRATE    528
LFPART      935
dtype: int64

In [66]:
#printing the mean, max and min for the unemployment rate
print(f'The average unemployment rate is:{(df['UNRATE'].mean()).round(1)}%, the maximum is: {(df['UNRATE'].max()).round(1)}%, and the minimum is: {(df['UNRATE'].min()).round(1)}%')

#printing the mean, max and min for labour force participation rate
print(f'The average labour force participation rate is:{(df['LFPART'].mean()).round(1)}%, the maximum is: {(df['LFPART'].max()).round(1)}%, and the minimum is: {(df['LFPART'].min()).round(1)}%')

The average unemployment rate is:5.7%, the maximum is: 14.8%, and the minimum is: 2.5%
The average labour force participation rate is:62.8%, the maximum is: 67.3%, and the minimum is: 58.1%

In [70]:
#part 4

#creating a new column with the decades
df['Decade'] = df['Year'] // 10 * 10

In [75]:


for i in range(1950, 2011, 10):
    group = df.loc[df['Decade'] == i]
    print(i, group['UNRATE'].count())
    if group['UNRATE'].count() != 120:
        continue
    avg = group['UNRATE'].mean()
    print(f'The average unemployment rate in the {i}s was {avg}')

1950 120
The average unemployment rate in the 1950s was 4.511666666666667
1960 120
The average unemployment rate in the 1960s was 4.779166666666667
1970 120
The average unemployment rate in the 1970s was 6.2175
1980 120
The average unemployment rate in the 1980s was 7.2725
1990 120
The average unemployment rate in the 1990s was 5.762500000000001
2000 120
The average unemployment rate in the 2000s was 5.541666666666667
2010 120
The average unemployment rate in the 2010s was 6.220833333333333

***
# Exercise 4: Daily stock-market returns

In this exercise, you will compute daily returns for the S&P 500 index and count
trading days with losses or large gains. The column `SP500` contains the index
values.

1.  Load `SP500.csv` from the `data/stockmarket` folder, parse `Date` as dates, and
    set it as the `DataFrame` index. Restrict the data to observations after
    January 1, 2020.

    *Hint:* Use `pd.read_csv(..., parse_dates=['Date'])` to automatically parse the
    strings in the `Date` column as dates.

2.  Compute daily returns in percent using
    [`pct_change()`](
    https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html
    )
    and store them in a new column `Return`. Explain why the first return is
    missing.

    *Hint:* Multiply the result of `pct_change()` by 100 to express returns in
    percent.

3.  Report the number and percentage of trading days with losses, i.e., negative
    returns. Exclude days with missing returns from the denominator.

    *Hint:* Summing a Boolean `Series` counts the number of `True` values. Use
    [`count()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.count.html)
    to count nonmissing observations.

4.  Report the number and percentage of trading days with gains of more than 5%.
5.  Report the number and percentage of days with negative returns on both the
    current and the previous trading day. A run of three loss days contributes
    two qualifying days. For the percentage, include only days with both returns
    observed.

    *Hint:* Use
    [`shift()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.shift.html)
    to obtain the previous trading day's return, and combine the two conditions
    using `&`.

In [ ]:
#part 1
import pandas as pd

# Relative path to data directory
DATA_PATH = '../../data'

file = f'{DATA_PATH}/stockmarket/SP500.csv'
df_sp500 = pd.read_csv(file, parse_dates=['Date'])
df_sp500 = df_sp500.set_index('Date')

Index(['SP500'], dtype='str')

In [110]:
#restricting the observations to after January 1, 2020

df_sp500 = df_sp500.loc[df_sp500.index > '2020-01-01']

In [111]:
#making a new column that calculates the percentage change in returns
df_sp500['Return'] = df_sp500['SP500'].pct_change() * 100

#The first column is empty because there is no change. It is the first value in the column
df_sp500

             SP500    Return
Date
2020-01-02  3257.9       NaN
2020-01-03  3234.9 -0.705976
2020-01-06  3246.3  0.352407
2020-01-07  3237.2 -0.280319
2020-01-08  3253.1  0.491165
...            ...       ...
2025-12-23  6909.8  0.455041
2025-12-24  6932.0  0.321283
2025-12-26  6929.9 -0.030294
2025-12-29  6905.7 -0.349211
2025-12-30  6896.2 -0.137568

[1507 rows x 2 columns]

In [112]:
#part 3

#counting all days with return observations
days_returns = df_sp500['Return'].count()
#counting all days with negative returns
days_loss = df_sp500.query('Return < 0')['Return'].count()

#calculating and printing the number of days with negative returns and the percentage of days with negativ returns
print(f'The number of days with negative returns is {days_loss} and the percentage of days with negative returns is {days_loss/days_returns*100:.2f}%')

The number of days with negative returns is 685 and the percentage of days with negative returns is 45.48%

In [ ]:
#uusing the same mathod as above to calculate the number of days with more than 5% returns + percentage
days_gain = df_sp500.query('Return > 5')['Return'].count()

print(f'The number of days with more than 5% return is {days_gain}, and the percentage of days with more than 5% return is {days_gain/days_returns*100:.2f}%')

The number of days with more than 5% return is 7, and the percentage of days with more than 5% return is 0.46%

In [ ]:
#Calculating the number of days with consecutive negative returns using the boolean condition

days_db_negative = df_sp500.query('Return < 0 & Return.shift() < 0')['Return'].count()

print(f'the number of observations of two days with consecutive negatvie returns are {days_db_negative}, and the percentage og consecutive negative days of all trading days is {days_db_negative/days_returns*100:.2f}%')

the number of observations of two days with consecutive negatvie returns are 296, and the percentage og consecutive negative days of all trading days is 19.65%

***
# Exercise 5: Working with string data (advanced)

Most of the data we deal with contain strings, i.e., text data (names, addresses, etc.). Often, such data is not in the format needed for analysis, and we have to perform additional string manipulation to extract the exact data we need. This can be achieved using the pandas
[string methods](https://pandas.pydata.org/docs/user_guide/text.html#string-methods).

To illustrate, we use the Titanic data set for this exercise.

1.  Load the Titanic data and restrict the sample to men. (This simplifies the task. Some
    married women's entries contain both their husband's name and their maiden name.)
2.  Print the first five observations of the `Name` column. As you can see, the data is stored in the format _"Last name, Title First name"_ where the title is something like Mr., Rev., etc.
3.  Split the `Name` column by `,` to extract the last name and the remainder as separate columns. You can achieve this using the
   [`partition()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.partition.html)
   string method.
4. Split the remainder (containing the title and first name) using the space
   character `" "` as separator to obtain individual columns for the title and
   the first name.

   *Hint:* The remainder starts with a space after the comma. Use `.str.strip()`
   to remove leading and trailing whitespace before splitting it.

5. Store the three data series in the original `DataFrame` (using the column names `FirstName`, `LastName`, and `Title`) and delete the `Name` column, which is no longer needed.
6. Finally, extract the ship deck from the values in `Cabin`. The ship deck is the first character in the string stored in `Cabin` (A, B, C, ...). You extract the first character using the
   [`get()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.get.html)
   string method. Store the result in the column `Deck`.

*Hint*: pandas's string methods can be accessed using the `.str` attribute. For example,
to partition values in the column `Name`, you need to use
```python
df['Name'].str.partition()
```

In [ ]:
#part 1
file = f'{DATA_PATH}/titanic.csv'

df = pd.read_csv(file)

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S

In [39]:
#restricting the sample to men
df = df.loc[df['Sex'] == 'male']

In [40]:
#part 2
#printing the first 3 rows of the 
print(df['Name'].head(3))

0     Braund, Mr. Owen Harris
4    Allen, Mr. William Henry
5            Moran, Mr. James
Name: Name, dtype: str

In [41]:
#splitting the names into parts by comma
parts = df['Name'].str.partition(',')
parts.head()

          0  1                      2
0    Braund  ,        Mr. Owen Harris
4     Allen  ,      Mr. William Henry
5     Moran  ,              Mr. James
6  McCarthy  ,          Mr. Timothy J
7   Palsson  ,   Master Gosta Leonard

In [42]:
#splitting the names into parts by space
more_parts = parts[2].str.partition('. ')
more_parts.head()

                       0   1              2
0                     Mr  .     Owen Harris
4                     Mr  .   William Henry
5                     Mr  .           James
6                     Mr  .       Timothy J
7   Master Gosta Leonard

In [43]:
#adding a new column with the first names
df['FirstName'] = more_parts[2]

In [44]:
#adding a column with the last names
df['LastName'] = parts[0]

In [45]:
#adding the titles to a seperate column
df['Title'] = more_parts[0]

In [ ]:
#dropping the name column
df = df.drop(columns = 'Name')

In [52]:
#extracting the ship deck from cabin
deck = df['Cabin'].str.get(0)
df['Deck'] = deck